---
title: "anonymous functions"
author: "Matt Rosinski"
date: "12/03/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
# Define echo_word as a lambda function: echo_word
echo_word = (lambda word1, echo: word1 * echo)

result = echo_word('hey', 5)

print(result)
```

```{r}
# Define echo_word as an anonymous function: echo_word
echo_word <-  function(word, echo) paste(c(rep(word, echo)),collapse = "")

result <- echo_word('hey', 5)

result
```

```{python}
# Create a list of strings: spells
spells = ["protego", "accio", "expecto patronum", "legilimens"]

# Use map() to apply a lambda function over spells: shout_spells
shout_spells = map(lambda item: item.upper() + '!!!', spells)

# Convert shout_spells to a list: shout_spells_list
shout_spells_list = list(shout_spells)

print(spells)
# Print the result
print(shout_spells_list)
```

# Using a filter
```{python}
# Create a list of strings: fellowship
fellowship = ['frodo', 'samwise', 'merry', 'pippin', 'aragorn', 'boromir', 'legolas', 'gimli', 'gandalf']

# Use filter() to apply a lambda function over fellowship: result
result = filter(lambda member:len(member) > 6, fellowship)

# Convert result to a list: result_list
result_list = list(result)

# Print result_list
print(result_list)
```

# An anonymous function is not required in R
```{r}
# Create a list of strings: fellowship
fellowship <-  c('frodo', 'samwise', 'merry', 'pippin', 'aragorn', 'boromir', 'legolas', 'gimli', 'gandalf')

fellowship[nchar(fellowship) > 6]

```

# Print tweets that match search string 'RT' in first 2 characters
```{python}
import pandas as pd

# Import Twitter data as DataFrame: df
tweets_df = pd.read_csv('./data/tweets.csv')

# Select retweets from the Twitter DataFrame: result
result = filter(lambda x: x[0:2] == 'RT', tweets_df['text'])

# Create list from filter object result: res_list
res_list = list(result)

# Print all retweets in res_list
for tweet in res_list:
    print(tweet)

```

```{python}
import pandas as pd

# Import Twitter data as DataFrame: df
tweets_df = pd.read_csv('./data/tweets.csv')

# Define count_entries()
def count_entries(df, col_name='lang'):
    """Return a dictionary with counts of
    occurrences as value for each key."""

    # Initialize an empty dictionary: cols_count
    cols_count = {}

    # Add try block
    try:
        # Extract column from DataFrame: col
        col = df[col_name]
        
        # Iterate over the column in DataFrame
        for entry in col:
    
            # If entry is in cols_count, add 1
            if entry in cols_count.keys():
                cols_count[entry] += 1
            # Else add the entry to cols_count, set the value to 1
            else:
                cols_count[entry] = 1
    
        # Return the cols_count dictionary
        return cols_count

    # Add except block
    except:
        'The DataFrame does not have a ' + col_name + ' column.'

# Call count_entries(): result1
result1 = count_entries(tweets_df, 'lang')

# Print result1
print(result1)
```

```{r}
library(reticulate)
py_discover_config()
```

# Raise a Value error is column not matched
```{python}
import pandas as pd

# Import Twitter data as DataFrame: df
tweets_df = pd.read_csv('./data/tweets.csv')
# Define count_entries()
def count_entries(df, col_name='lang'):
    """Return a dictionary with counts of
    occurrences as value for each key."""
    
    # Raise a ValueError if col_name is NOT in DataFrame
    if col_name not in df.columns:
        raise ValueError('The DataFrame does not have a ' + col_name + ' column.')

    # Initialize an empty dictionary: cols_count
    cols_count = {}
    
    # Extract column from DataFrame: col
    col = df[col_name]
    
    # Iterate over the column in DataFrame
    for entry in col:

        # If entry is in cols_count, add 1
        if entry in cols_count.keys():
            cols_count[entry] += 1
            # Else add the entry to cols_count, set the value to 1
        else:
            cols_count[entry] = 1
        
        # Return the cols_count dictionary
        return cols_count

# Call count_entries(): result1
result1 = count_entries(df=tweets_df, col_name='lang')

# Print result1
print(result1)
```

z