---
title: "Apply functions to every column"
author: "Matt Rosinski"
date: "2023-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Using Base R
```{r}
x <- data.frame(matrix(runif(5 * 1e4), ncol = 5))

head(x)

medians <- vapply(x, median, numeric(1))

for (i in seq_along(medians)) {
    x[[i]] <- x[[i]] - medians[[i]]
}

head(x)
```


```{r}
library(dplyr)
x <- data.frame(matrix(runif(5 * 1e4), ncol = 5))
head(x)

# Subtract column medians from every value
x <- x %>%
    mutate(across(everything(), ~ . - median(.)))
head(x)

# Summarize the mean of every column
x %>% 
    summarise(across(everything(), mean))

```

```{python}
import pandas as pd
import numpy as np

# Create a DataFrame with 5 columns and 50,000 rows of random uniform values
x = pd.DataFrame(np.random.uniform(size=(50000, 5)))

x.head()

```

```{python}
import pandas as pd

# Subtract column medians from every value
x_centred = x.apply(lambda col: col - col.median())
x_centred.head()

# Summarize the mean of every column
x_means = x_centred.mean()
x_means.head()

```

