---
title: "object attributes"
author: "Matt Rosinski"
date: "2023-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)

dplyr_ns <- getNamespace("dplyr")

ls(dplyr_ns)

length(dplyr_ns)

a <- "abcd"

str(a)

typeof(a)



```

```{python}

import pandas as pd

import os

os.sep

os.sep = '/'

os.sep


dir(pd)

type(int)

type(type)

str(123)

type(list('abcd'))

a = 'abcd' # identifier = name = variable or function
  # search is LEGB (local, enclosing, global, built-in)
  
dir(a)

dir(a.strip())

dir(a.strip().islower())

```
```{python}
mylist = [10, 20, 30]
sum(mylist)  # sum is a function, takes a list as an argument

mylist.sum()

mylist.pop()

mylist

# Ruby doesn't have functions separate to methods

len(mylist)

mylist.__len__()

# Rather than write methods with the same name on many objects
# Some general functions were written that apply on many objects
# Use methods first and functions only when the methods are not available

help(list)

dir(mylist)

dir(list)

```
```{python}

# Foo inherits from object
class Foo(object):
    pass

type(Foo)

# Using the Foo class to create a Foo object
# f is an instance of Foo
f = Foo()

type(f)

dir(Foo)

dir(f)
```
```{python}

f = Foo()

# vars()  # globals()
# def bar():
#     vars() # locals()
    
# dictionary
vars(f)

f.x = 100
f.y = [10, 20, 30]

dir(f)

vars(f)

g = Foo()

dir(g)
vars(g)

g.a = {'a':1, 'b':2, 'c':3}
g.b = {10, 20, 30, 40, 50}

vars(g)

vars(f)
```

```{python}

class Foo(object):
    def __init__(self):
        self.x = 100
        self.y = [10, 20, 30]

f = Foo()

vars(f)

dir(f.y)

f.x = {10, 20, 30}
dir(f.x)

vars(f)

f.y.pop()
f.x.pop()

vars(f)

f.x.pop()

vars(f)

f.y.append(40)

vars(f)

dir(f.x)

f.x.add(99)

vars(f)

```
```{python}

class Foo(object):
    def __init__(self, x=99, y=66, *args):
        self.x = x
        self.y = y
        self.args = args

f = Foo([10, 20 ,30], [100, 200, 300], "two", 3)

g = Foo()

vars(f)

vars(g)

```

```{python}

computers = [{'brand':'Apple', 'year':2014},
            {'brand':'HP', 'year':2016},
            {'brand':'Lenovo', 'year':2016},
            {'brand':'Apple', 'year':2010}]
    
computers        
            
```

```{python}
for one_computer in computers:
    print(f"{one_computer['brand']}, from {one_computer['year']}")
    
```

```{python}
for one_computer in computers:
    if one_computer['year'] == 2016:
            print(f"{one_computer['brand']}, from {one_computer['year']}")

```

```{python}
class Computer(object):
    def __init__(self, brand, year):
        self.brand = brand
        self.year = year

c1 = Computer('Apple', 2014)
c2 = Computer('HP', 2016)
c3 = Computer('Lenovo', 2016)
c4 = Computer('Apple', 2010)
```

```{python}
my_computers = [c1, c2, c3, c4]

# for one_computer in my_computers:
#     print(f"{one_computer.brand}, from {one_computer.year}")

[print(f"{one_computer.brand}, from {one_computer.year}") for one_computer in my_computers]

```

# Ice-cream objects

```{python}

class Scoop():
    def __init__(self, flavour):
        self.flavour = flavour

s1 = Scoop(flavour="chocolate")

s1.flavour
vars(s1)

s2 = Scoop("vanilla")
s3 = Scoop("coffee")

for one_scoop in [s1, s2, s3]:
    print(one_scoop.flavour)

```
```{python}
class Bowl(object):
    total_scoops = 0
    
    def __init__(self):
        self.scoops = []
    
    # Set maximum number of scoops in a bowl
    def add_scoops(self, *args):
        if Bowl.total_scoops >= 3:
            return
        else:
            Bowl.total_scoops += 1
            self.scoops += args
    
    def flavours(self):
        return ', '.join([scoop.flavour for scoop in self.scoops])

b1 = Bowl()

vars(b1)

b1.add_scoops(s1)
b1.add_scoops(s2)
b1.add_scoops(s3)

b1.total_scoops

b1.add_scoops(s1)

b1.total_scoops

b1.scoops[0].flavour
b1.scoops[1].flavour

b1.flavours()
```
## Bank Account objects

```{python}

class Person(object):
    def __init__(self, name, email, phone):
        self.name = name
        self.email = email
        self.phone = phone
        self.account = []
    
    def add_account(self, *args):
        self.account += args
    
    def all_balances(self, *args):
        return [sum(account.transactions) for account in self.account]
    
    def current_total_balance(self):
        return sum([sum(account.transactions) for account in self.account])
    # 
    def average_transaction_amount(self):
    #     all_transactions = [one_transaction for one_account in self.account
    #                         for one_transaction in one_account.transactions]
        all_transactions = []
        for one_account in self.account:
            for one_transaction in one_account.transactions:
                all_transactions.append(one_transaction)

        print(all_transactions)
        return sum(all_transactions) / len(all_transactions)
                            
class BankAccount(object):
    def __init__(self):
        self.transactions = []
    
    def transaction(self, value):
        self.transactions.append(value)
        


# Create people records
p1 = Person("Mark", "mark@yahoo.com", "442-234-4323")

vars(p1)

p2 = Person("Heidi", "heidi@hotmail.com", "596-345-6474")

p3 = Person("Matt", "matt@xycd.com", "353-356-9965")

# Create accounts and attached to people records
b1 = BankAccount()
p1.add_account(b1)
b1.transaction(-100)
b1.transaction(20)
b1.transaction(234)

b2 = BankAccount()
p1.add_account(b2)
b2.transaction(10)
b2.transaction(20)
b2.transaction(30)
b2.transaction(1)

b3 = BankAccount()
p2.add_account(b3)
b3.transaction(1)
b3.transaction(2)
b3.transaction(3)
b3.transaction(10)

b1.transactions
b2.transactions
b3.transactions

p1.all_balances()
p1.current_total_balance()

p2.all_balances()
p2.current_total_balance()

p1.average_transaction_amount()


sum([-100, 20, 234, 10, 20, 30, 1])/len([-100, 20, 234, 10, 20, 30, 1])

```

```{python}

class BankAccount(object):
    def __init__(self):
        self.transactions = []
        
        
b1 = BankAccount()

vars(b1)

b1.transactions.append(-100)

b1.transactions.append(20)
b1.transactions.append(234)


# Balance
sum(b1.transaction)

# Number of transactions
len(b1.transaction)

# Average transaction
sum(b1.transaction)/len(b1.transaction)



```

## Foo objects

```{python}
class Foo:
    def __init__(self, x):
        self.x = x
    
    def x2(self):
        return self.x * 2
    # Not pythonic
    # def get_x(self):        # getter or accessor
    #     return self.x
    # 
    # def set_x(self, new_x):  # setter or mutator
    #     self.x = new_x

f1 = Foo(2)

f1.x2()

f2 = Foo(4)
vars(f2)
f2.x2()

# No need to use getters and setters in Python because we can get attributes with this:
f1.x
# and set attributes like so:
f1.x = 40

f1.x

```

## Bookstore objects
```{python}
class Book(object):
    def __init__(self, title, author, price=30):
        self.title = title
        self.author = author
        self.price = price
    
    def nice_author_name(self):
        return ', '.join(reversed(self.author.split()))
    
    def price_with_tax(self):
        return self.price * 1.15

b1 = Book('Title1', 'John Smith')
b2 = Book('Title2', 'David Cohen')
b3 = Book('Title', 'Doug Trainer', 25)


```

```{python}
b1.price

b2.price

b3.price

b3.author

b3.nice_author_name()

b3.price_with_tax()

```

```{python}
# has-a relationship -- composition
# Bookshelf has-a book

class Bookshelf(object):
    def __init__(self):
        self.books = []
        
    def add_books(self, *args):
        self.books += args
        
    def total_price(self):
        return sum([one_book.price 
                for one_book in shelf.books])

shelf = Bookshelf()
shelf.add_books(b1, b2, b3)
```

```{python}
shelf.books

shelf.books[0].author

sum([one_book.price for one_book in shelf.books])

shelf.total_price()

```

## Shopping cart objects
```{python}
class ShoppingCart:
    def __init__(self):
        self.items = {}
            
    # Methods using tuples
    def add_r(self, name, price, new_quantity):
        if name in self.items:
            price, previous_quantity = self.items[name]
            self.items[name] = (price, previous_quantity + new_quantity)
        else:
            self.items[name] = (price, new_quantity)
    
    def remove_r(self, name):
        if name in self.items:
            price, quantity = self.items[name]
            if quantity == 1:
                self(self.items[name])
            else:
                self.items[name] = (price, quantity - 1)
    
    def view_cart_r(self):
        for item, (price, quantity) in self.items.items():
            item_total = price * quantity
            print(f'{item:<10s} {quantity:<5d} x {price:>6.2f} = {item_total:>7.2f}')
    
    
    def total_r(self):
        return sum([price * quantity for price, quantity in self.items.values()])
    
    # Methods not using tuples 
    def add(self, name, price, quantity):
        if name in self.items:
            self.items[name]['quantity'] += quantity
        else:
            self.items[name] = {'quantity': quantity, 'price': price}
    
    def remove(self, name):
        if name in self.items:
            if self.items[name]['quantity'] == 1:
                del self.items[name]
            elif self.items[name]['quantity'] > 1:
                self.items[name]['quantity'] -= 1
    
    def view_cart(self):
        for item in self.items:
            item_quantity = self.items[item]['quantity']
            item_price = self.items[item]['price']
            item_total = item_quantity * item_price
            print(f'{item:<10s} {item_quantity:<5d} x {item_price:>6.2f} = {item_total:>7.2f}')
    
    def total(self):
        totals = []
        for item in self.items:
            totals.append(self.items[item]['price'] * self.items[item]['quantity'])
        print(f'Total Due: ${sum(totals)}')


sc = ShoppingCart()

sc.add_r('book', 30, 1)
sc.add_r('toothbrush', 3.30, 4)
sc.add_r('toothbrush', 3.30, 4)
sc.total_r()

sc.remove_r('toothbrush')
sc.total_r()
sc.remove_r('toothbrush')
sc.total_r()

sc.view_cart_r()


sc.add('book', 30, 1) # name, price-per-unit, quantity
sc.add('toothbrush', 3.30, 4)

sc.view_cart()

sc.remove('toothbrush')  #removes one toothbrush or item altogether

sc.view_cart()

```


```{python}
sc.add('baked beans', 2.20, 10)

sc.total()

```

```{python}

class Person:
    population = 0  # Class attribute
    
    def __init__(self, name):
        self.name = name
        Person.population += 1

p1 = Person("Max")
p2 = Person("Simon")
p2.name

p1.population
p2.population
```


## R6 class objects
```{r}

library(R6)

# Define Book class
Book <- R6Class("Book",
  public = list(
    title = NULL,
    author = NULL,
    price = 30,
    initialize = function(title, author, price = 30) {
      self$title <- title
      self$author <- author
      self$price <- price
    },
    
    nice_author_name = function() {
      return(paste(rev(strsplit(self$author, " ")[[1]]), collapse = ", "))
    },
    
    price_with_tax = function() {
      return(self$price * 1.15)
    }
  )
)

# Define Bookshelf class
Bookshelf <- R6Class("Bookshelf",
  public = list(
    books = NULL,
    initialize = function() {
      self$books <- list()
    },
    
    add_books = function(...) {
      self$books <- c(self$books, list(...))
    },
    
    total_price = function() {
      return(sum(sapply(self$books, function(one_book) one_book$price)))
    }
  )
)

# Create some books and a bookshelf
book1 <- Book$new("The Great Gatsby", "F. Scott Fitzgerald", 20)
book2 <- Book$new("To Kill a Mockingbird", "Harper Lee", 25)
bookshelf <- Bookshelf$new()

# Add books to the bookshelf
bookshelf$add_books(book1)
bookshelf$add_books(book2)

# Get the total price of the books on the bookshelf
bookshelf$total_price()


```

