---
title: "get streaks"
output: html_document
date: "2022-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(timetk)
library(tidyquant)

# Get stock prices for a stock from Yahoo
apple_stock_prices <- tq_get("AAPL")

apple_stock_prices %>% 
    summarise(
        start_date = min(date),
        end_date = max(date)
    )

get_streaks <- apple_stock_prices %>% 
    select(date, close) %>% 
    mutate(
        up            = if_else(is.na(diff_vec(close) > 0), FALSE, diff_vec(close) > 0),
        cumul_streak  = cumsum(up) * up,
        detect_change = diff_vec(cumul_streak),
        adjust_streak = ifelse(detect_change < 0, detect_change, NA)
    ) %>% 
    fill(adjust_streak, .direction = "down") %>% 
    mutate(
        adjust_streak = ifelse(is.na(adjust_streak), 0, adjust_streak)*up,
        streak = cumul_streak + adjust_streak
        )

get_streaks %>% 
    count(streak) %>% 
    mutate(pct = n/sum(n)) %>% 
    ggplot(aes(as_factor(streak), pct)) +
    geom_col(fill = "#00A5B3") +
    scale_y_continuous(labels = scales::label_percent()) +
    # scale_x_binned() +
    labs(
        title = "Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)",
        x = "Consecutive day by day increases in share price",
        y = "Probability"
    ) +
    theme_minimal()

```



```{python}
import pandas as pd
import matplotlib.pyplot as plt

df = r.apple_stock_prices

df.info()

df['up'] = df['close'].diff().fillna(0) > 0

s = df['up']

df['streak'] = (s
                 .mul(s.cumsum())
                 .diff()
                 .where(lambda x: x <0)
                 .ffill()
                 .add(s.cumsum(), fill_value=0))
                 

df.head()


ax = (df
        ['streak']
        .value_counts(normalize=True)
        .mul(100).round(1)
        .plot.bar(figsize=(8, 4), 
        title="Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)",
        xlabel="Probability",
        ylabel="Consecutive day by day increases in share price")

ax.get_figure().savefig('apple_price_increase_streaks.png')

ax.get_figure().show()
```


```{python}
# a bar plot of the data
x = (df
        ['streak']
        .value_counts(normalize=True)
        .mul(100)
        .round(1)
        .to_numpy()
        )

print(x)
_ = plt.bar(x, height=10)


plt.xlabel('Consecutive day by day increases in share price')
plt.ylabel('Probability')
plt.title('Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)')
plt.ylim(0, 100)
plt.grid(True)
plt.show()

plt.close()
```


```{python}
plt.plot()
plt.title('Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)')
plt.xlabel('Consecutive day by day increases in share price')
plt.ylabel('Probability %')

# Tweak spacing to prevent clipping of ylabel
plt.subplots_adjust(left=0.15)
plt.show()
```


```{python}
import numpy as np

# Fixing random state for reproducibility
np.random.seed(19680801)

mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

type(x)

# the histogram of the data
n, bins, patches = plt.hist(x, 50, density=True, facecolor='g', alpha=0.75)


plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.xlim(40, 160)
plt.ylim(0, 0.03)
plt.grid(True)
plt.show()



```

