---
title: "iterators"
author: "Matt Rosinski"
date: "2023-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
# Create a list of squared numbers using list comprehension
squared_numbers = [x**2 for x in range(10)]
squared_numbers
```
```{python}
res = []

for x in range(10): 
    res.append(x**2)

res

```
```{python}
squared_numbers = list(map(lambda x: x**2, range(10)))
squared_numbers
```
```{python}
import numpy as np

squared_numbers = np.square(np.arange(10)).tolist()
squared_numbers

```


```{r}
(squared_numbers = sapply(0:9, function(x) x^2))
```


```{r}
# Note that we use the ~ symbol to define a lambda or anonymous 
# function that takes a single argument (in this case, .)

library(purrr)
(squared_numbers = map_dbl(0:9, ~ .^2))
```
```{r}
# This approach takes advantage of R's built-in operators and vectorization 
# capabilities to perform the operation, without the need for explicit 
# function calls.

(squared_numbers <- (0:9)^2)

```

