---
title: "indexing"
author: "Matt Rosinski"
date: '2022-04-04'
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
import pandas as pd

temperatures = pd.read_csv("data/temperatures.csv")

# Look at temperatures
print(temperatures)

# Index temperatures by city
temperatures_ind = temperatures.set_index("city")

# Look at temperatures_ind
print(temperatures_ind)

# Reset the index, keeping its contents
print(temperatures_ind.reset_index())

# Reset the index, dropping its contents
print(temperatures_ind.reset_index(drop = True))
```

# Subsetting with indexes and loc
```{python}
# Make a list of cities to subset on
cities = ["Moscow", "Saint Petersburg"]

# Subset temperatures using square brackets
print(temperatures[temperatures["city"].isin(cities)])

# Subset temperatures_ind using .loc[]
print(temperatures_ind.loc[cities])
```

# Multi-level indexes
```{python}
# Index temperatures by country & city
temperatures_ind = temperatures.set_index(["country", "city"])

# List of tuples: Brazil, Rio De Janeiro & Pakistan, Lahore
rows_to_keep = [("Brazil", "Rio De Janeiro"), ("Pakistan", "Lahore")]

# Subset for rows to keep
print(temperatures_ind.loc[rows_to_keep])
```

# Sort using indexes
```{python}
# Sort temperatures_ind by index values
print(temperatures_ind.sort_index())

# Sort temperatures_ind by index values at the city level
print(temperatures_ind.sort_index(level = ["city"]))

# Sort temperatures_ind by country then descending city
print(temperatures_ind.sort_index(level = ["country", "city"], ascending = [True, False]))
```

# Sort using values
```{python}

# Sort temperatures_ind by country then descending city
print(temperatures.sort_values(["country", "city"], ascending = [True, False]))
```

# Slicing rows
```{python}
# Sort the index of temperatures_ind
temperatures_srt = temperatures_ind.sort_index()

# Subset rows from Pakistan to Russia
print(temperatures_srt.loc["Pakistan":"Russia"])

# Try to subset rows from Lahore to Moscow (produces an error!)
print(temperatures_srt.loc["Lahore":"Moscow"])

# Subset rows from Pakistan, Lahore to Russia, Moscow - use tuples
print(temperatures_srt.loc[("Pakistan", "Lahore"):("Russia", "Moscow")])

```

# Slicing rows and columns
```{python}
# Subset rows from India, Hyderabad to Iraq, Baghdad
print(temperatures_srt.loc[("India", "Hyderabad"):("Iraq", "Baghdad")])

# Subset columns from date to avg_temp_c
print(temperatures_srt.loc[:, "date":"avg_temp_c"])

# Subset in both directions at once
print(temperatures_srt.loc[("India", "Hyderabad"):("Iraq", "Baghdad"),"date":"avg_temp_c"])
```

# Slicing by dates
```{python}
# Use Boolean conditions to subset temperatures for rows in 2010 and 2011
temperatures_bool = temperatures[(temperatures["date"] >= "2010-01-01") & (temperatures["date" ]<= "2011-12-31")]
print(temperatures_bool)

# Set date as the index and sort the index
temperatures_ind = temperatures.set_index("date").sort_index()

# Use .loc[] to subset temperatures_ind for rows in 2010 and 2011
print(temperatures_ind.loc["2010":"2012"])

# Use .loc[] to subset temperatures_ind for rows from Aug 2010 to Feb 2011
print(temperatures_ind["2010-08":"2011-03"])
```

# Slicing by row and column number
```{python}
# Get 23rd row, 2nd column (index 22, 1)
print(temperatures.iloc[23,1])

# Use slicing to get the first 5 rows
print(temperatures.iloc[:5,])

# Use slicing to get columns 3 to 4
print(temperatures.iloc[:, 2:5])

# Use slicing in both directions at once
print(temperatures.iloc[:5, 2:5])
```


```{python}
# Add a year column to temperatures

temperatures.info()
temperatures["date"] = pd.to_datetime(temperatures["date"])
temperatures.info()

```

# Pivot tables
```{python}
import pandas as pd
temperatures = r.temperatures

temperatures["year"] = temperatures["date"].dt.year

# Pivot temperatures
temp_by_country_city_vs_year = temperatures.pivot_table("avg_temp_c", index = ["country", "city"], columns = "year")

print(temp_by_country_city_vs_year)
```

# Subsetting on a pivot table
```{python}
# Subset for Egypt to India
temp_by_country_city_vs_year.loc["Egypt":"India"]

# Subset for Egypt, Cairo to India, Delhi
temp_by_country_city_vs_year.loc[("Egypt", "Cairo"): ("India", "Delhi")]

# Subset for Egypt, Cairo to India, Delhi, and 2005 to 2010
temp_by_country_city_vs_year.loc[("Egypt", "Cairo"): ("India", "Delhi"), 2005:2010]

```

# Calculating on a pivot table
```{python}
# Get the worldwide mean temp by year
mean_temp_by_year = temp_by_country_city_vs_year.mean()

# Filter for the year that had the highest mean temp
print(mean_temp_by_year[mean_temp_by_year == mean_temp_by_year.max()])

# Get the mean temp by city
mean_temp_by_city = temp_by_country_city_vs_year.mean(axis="columns")

# Filter for the city that had the lowest mean temp
print(mean_temp_by_city[mean_temp_by_city == mean_temp_by_city.min()])
```


```{r}
temperatures <- read_csv(file = "https://bit.ly/load-temperatures") %>% select(-...1)

head(temperatures)
```

```{r}
library(tidyverse)
library(lubridate)

temperatures %>%
    mutate(year = year(date)) %>% 
    group_by(country, city, year) %>%
    summarise(mean = mean(avg_temp_c, na.rm = TRUE)) %>%
    pivot_wider(names_from = year, values_from = mean)

```


```{r}
mtcars

```

```{r}
library(tidyquant)

temperatures

temperatures %>% as_tibble() %>%
    mutate(year = year(ymd_hms(date))) %>% 
    
    pivot_table(.rows    = c(country, city),
                .columns = year, 
                .values  = ~ mean(avg_temp_c, na.rm = TRUE))

FANG
FANG %>%
    pivot_table(
        .rows       = c(symbol, ~ QUARTER(date)),
        .columns    = ~ YEAR(date),
        .values     = ~ PCT_CHANGE_FIRSTLAST(adjusted)
    )
```

