---
title: "summarisation"
author: "Matt Rosinski"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mtcars
```

# Summarisation
```{python}

mtcars = r.mtcars
# Print the head of the sales DataFrame
print(mtcars.head())

# Print the info about the sales DataFrame
print(mtcars.info())

# Print the mean of weekly_sales
print(mtcars["mpg"].mean())

# Print the median of weekly_sales
print(mtcars["mpg"].median())

# Print the maximum of the date column
print(sales["date"].max())

# Print the minimum of the date column
print(sales["date"].min())

print(mtcars.head())
```


# Aggregate method
## Multiple columns and functions
```{python}
# Import NumPy and create custom IQR function
import numpy as np
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Update to print IQR and median of temperature_c, fuel_price_usd_per_l, & unemployment
print(mtcars[["mpg", "hp", "disp"]].agg([iqr,np.median]))


```

# Cumulative functions
```{python}
# Sort sales_1_1 by date
sales_1_1 = sales_1_1.sort_values("date", ascending = True)
print(sales_1_1.head())
# Get the cumulative sum of weekly_sales, add as cum_weekly_sales col
sales_1_1['cum_weekly_sales'] = sales_1_1['weekly_sales'].cumsum()

# Get the cumulative max of weekly_sales, add as cum_max_sales col
sales_1_1['cum_max_sales'] = sales_1_1['weekly_sales'].cummax()

# See the columns you calculated
print(sales_1_1[["date", "weekly_sales", "cum_weekly_sales", "cum_max_sales"]])

```

