---
title: "case-when-assignment"
author: "Matt Rosinski"
date: "2022-09-21"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Selectively assign values to rows that meet a certain criteria
```{r}
library(tidyverse)

# First generate some dummy data for the example
set.seed(42)
df <- tibble(
    index_ = seq(1, 100),
    value = rnorm(100, mean = 50, sd = 10),
    category = 'init')
```


```{r}
# We can use a boolean selection filter but this can be come quite verbose
df2 = df

filt1 <- df2['value'] > 60
filt2 <- df2['value'] < 40
filt3 <- (df2['value'] > 40) & (df2['value'] < 60)

df2[filt1, 'category'] <- 'high'
df2[filt2, 'category'] <- 'low'
df2[filt3, 'category'] <- 'med'

df2 %>% count(category)
```

# dplyr has a case_when function to perform the same job
```{r}
# Recommend using dplyr case_when statement for more flexibility and efficency
df3 <- df %>%
    mutate(
        category = case_when(
            value > 60 ~ 'high',
            value < 40 ~ 'low',
            TRUE ~ 'med'
        )
    )

df3 %>% count(category)

```

# In pandas we can also use Boolean Selection Assignment
```{python}
import pandas as pd

df = r.df
df2 = df.copy()

# Boolean selection in pandas looks very similar to R
filt1 = df2['value'] > 60
filt2 = df2['value'] < 40
filt3 = (df2['value'] > 40) & (df2['value'] < 60)

# Note the additional use of the loc operator
df2.loc[filt1, 'category'] = 'high'
df2.loc[filt2, 'category'] = 'low'
df2.loc[filt3, 'category'] = 'med'

df2.value_counts('category')
```


```{python}
# numpy has the where() function that can be used 
# in a similar fashion to the dplyr case_when() function
import numpy as np

# We make use of the filters from the preceding cell

df3 = df.copy()
df3['category'] = np.where(filt1, 'high', 
                  np.where(filt2, 'low', 'med') )

df3.value_counts('category')
```

# In the tidyverse we can use a case_when statement
```{r}

# One of the challenges of learning a new programming language is not only
# that you need to learn a new syntax but in some cases the new descriptions
# of what is happening.  Boolean selection assignment is just not a phrase
# I was familiar with until learning Python.  In SQL and R I referred to this 
# as case when or conditional assignment statements.  Of course, they are 
# equivalent but out ears are not tuned to the way people describe things in
# new sub-fields.
```

