---
title: "Causal Impact"
author: "Matt Rosinski"
date: "2023-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(CausalImpact)
library(tidyverse)

set.seed(2023)

x1 <- 100 + arima.sim(model = list(ar = 0.999), n = 100)
y <- 1.2 * x1 + rnorm(100)
y[71:100] <- y[71:100] + 10
data <- cbind(y, x1)

# data
# dim(data)
# class(x1)
# matplot(data, type = 'l')

pre.period <- c(1, 70)

post.period <- c(71, 100)

impact <- CausalImpact(data, pre.period, post.period)

plot(impact) + theme_minimal(base_size = 12) +
    labs(title = "Measuring the causal impact of changes to a system")

```

```{r}
summary(impact)

```

```{python}
from causalimpact import CausalImpact
import numpy as np
import pandas as pd
from statsmodels.tsa.arima_process import arma_generate_sample
import matplotlib.pyplot as plt

np.random.seed(2023)

x1 = arma_generate_sample(ar=[0.999], ma=[0.9], nsample=100) + 100
y = 1.2 * x1 + np.random.randn(100)

y[71:100] = y[71:100] + 10
data = pd.DataFrame(np.array([y, x1]).T, columns=["y","x1"])
#
# print(data)
# print(data.shape)
# print(type(x1))

pre_period = [0,69]
post_period = [71,99]

impact = CausalImpact(data, pre_period, post_period)

impact.run()

impact.plot()

```

```{python}
impact.summary(output = 'summary')

```


