---
title: "get streaks"
output: html_document
date: "2022-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(timetk)
library(tidyquant)

# Get stock prices for a stock from Yahoo
apple_stock_prices <- tq_get("AAPL")

apple_stock_prices %>% 
    summarise(
        start_date = min(date),
        end_date = max(date)
    )

get_streaks <- apple_stock_prices %>% 
    select(date, close) %>% 
    mutate(
        up            = if_else(is.na(diff_vec(close) > 0), FALSE, diff_vec(close) > 0),
        cumul_streak  = cumsum(up) * up,
        detect_change = diff_vec(cumul_streak),
        adjust_streak = ifelse(detect_change < 0, detect_change, NA)
    ) %>% 
    fill(adjust_streak, .direction = "down") %>% 
    mutate(
        adjust_streak = ifelse(is.na(adjust_streak), 0, adjust_streak)*up,
        streak = cumul_streak + adjust_streak
        )

get_streaks %>% 
    count(streak) %>% 
    mutate(pct = n/sum(n)) %>% 
    ggplot(aes(as_factor(streak), pct)) +
    geom_col(fill = "#00A5B3") +
    scale_y_continuous(labels = scales::label_percent()) +
    labs(
        title = "Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)",
        x = "Consecutive day by day increases in share price",
        y = "Probability"
    ) +
    theme_minimal()

```



```{python}
import pandas as pd
import matplotlib.pyplot as plt

df = r.apple_stock_prices

df['up'] = df['close'].diff().fillna(0) > 0

s = df['up']

df['streak'] = (s
                 .mul(s.cumsum())
                 .diff()
                 .where(lambda x: x <0)
                 .ffill()
                 .add(s.cumsum(), fill_value=0))

df.head(10)
```


```{python}
ax = (df['streak']
        .value_counts(normalize=True)
        .mul(100).round(1)
        .plot.bar(figsize=(8, 4), 
        title="Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)",
        xlabel="Probability",
        ylabel="Consecutive day by day increases in share price"))

ax.get_figure().savefig('apple_price_increase_streaks.png')


```


```{python}
# a bar plot of the data
plt.close()

streak_counts = (df
                    ['streak']
                    .value_counts(normalize=True)
                    .mul(100)
                    .round(1)
                    )

x = streak_counts.index
y = streak_counts.values

fig, ax = plt.subplots()
bar_obj = ax.bar(x=x, height=y)

_ = plt.bar(x, height=y)
_ = plt.xlabel('Consecutive day by day increases in share price')
_ = plt.ylabel('Probability %')
_ = plt.title('Chances of Consecutive Increases in Closing Share Price (Apple 2012-22)')
plt.grid(True)
plt.show()

```



