---
title: "fill by group"
author: "Matt Rosinski"
date: "2022-10-10"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Fill missing values by group
```{python}
import numpy as np
import pandas as pd

df = pd.DataFrame({'item': ['z', 'x', 'y', 'x', 'x', 'y', 'x', 'y', 'y', 'z'],
                   'quantity': [2, 7, 1, 9, np.nan, 4, 21,  np.nan, 9,  np.nan]})

df['ffill'] = df.groupby('item')['quantity'].ffill()
df

```

```{r}
library(tidyverse)

df <- tribble(
    ~item, ~quantity,
    'z',   2,
    'x',   7,
    'y',   1,
    'x',   9,
    'x',   NA,
    'y',   4,
    'x',   21,
    'y',   NA,
    'y',   9,
    'z',   NA
)

ffill <- df %>% 
    group_by(item) %>%
    fill(quantity, .direction = "down") %>% 
    ungroup() %>% 
    pull(quantity)



df %>% 
  group_by(item) %>% 
  fill(quantity, .direction = "down") %>% 
  ungroup()












df %>% 
    mutate(ffill = ffill)
```

