---
title: "anonymous-functions"
author: "Matt Rosinski"
date: "3/8/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
fellowship = ['frodo', 'samwise', 'merry', 'pippin', 'aragorn', 'boromir', 'legolas', 'gimli', 'gandalf']

# Use filter() to apply a lambda function over fellowship: result
result = filter(lambda member:len(member) > 6, fellowship)

# Convert result to a list: result_list
result_list = list(result)

# Print result_list
print(result_list)
```

```{r}

fellowship <- c('frodo', 'samwise', 'merry', 'pippin', 'aragorn', 'boromir', 'legolas', 'gimli', 'gandalf')

fellowship[nchar(fellowship) > 6]

```
# Reduce a list of jedi names into one 
```{python}
from functools import reduce

# Create a list of strings: stark
jedi = ['luke', 'obiwan', 'yoda', 'anikan', 'rey']

# Use reduce() to apply a lambda function over stark: result
result = reduce(lambda item1, item2: item1 + item2, jedi)

print(result)
```

```{r}
library(purrr)

jedi <- c('luke', 'obiwan', 'yoda', 'anikan', 'rey')

# There are some simple functions for pasting strings in R (see also str_c)
result <- paste0(jedi,collapse = "")

# Base R and purrr have a Reduce and reduce function that work similarly
result <- reduce(jedi, paste0, collapse = "")  # The purrr version shown here

result
```


```{r}
S <- cards()
A <- subset(S, suit == "Heart")
B <- subset(S, rank == "A" )
intersect(A, B)

?intersect()

(x <- c(sort(sample(1:20, 9)), NA))
(y <- c(sort(sample(3:23, 7)), NA))
union(x, y)
intersect(x, y)
setdiff(x, y)
setdiff(y, x)
setequal(x, y)



```

