---
title: "rolling mean"
author: "Matt Rosinski"
date: "2022-07-16"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Create a dataframe with rolling average snowfall over the last 5 days
```{python}
import pandas as pd
# url = 'https://raw.githubusercontent.com/mattharrison/datasets/' +\
#     'master/data/alta-noaa-1980-2019.csv'
    
alta_df = pd.read_csv(url)
    
dates = pd.to_datetime(alta_df.DATE)

snow = (alta_df
        .SNOW
        .rename(dates))
        
rolling_mean = (snow
 .rolling(5)
 .mean()
)

frame = {'snow': snow, 'rolling_mean': rolling_mean}
pd.DataFrame(frame).head(10)
```
```{r}
url <-  'https://raw.githubusercontent.com/mattharrison/datasets/master/data/alta-noaa-1980-2019.csv'
alta_df <- read_csv(url)
```

```{r}
library(timetk)
library(tidyverse)
library(reticulate)

alta_df <- py$alta_df

alta_df %>%
    select(DATE, SNOW) %>%
    mutate(rolling_mean = slidify_vec(.x = SNOW, 
                           .f = ~ mean(.x, na.rm = TRUE), 
                           .period = 5, 
                           .align = 'right'))

```

```{python}
# Aggregate values are different levels
max_snow = (snow
 .resample('MS')
 .max())

mean_snow = (snow
 .resample('MS')
 .mean())
 
 frame = {'max_snow': max_snow, 'mean_snow': mean_snow}
pd.DataFrame(frame)
.inde
.head(10)
 
# mean_snow
```


```{r}
library(lubridate)

alta_df %>%
    select(DATE, SNOW) %>%
    mutate(DATE = ymd(DATE)) %>%
    summarise_by_time(.date_var = DATE,
                      .by = "month", .type = "floor",
                      max_snow = max(SNOW, na.rm = TRUE),
                      mean_snow = mean(SNOW, na.rm = TRUE)
                      )
```

```{r}
m4_daily %>%
    # group_by(id) %>%
    summarise_by_time(
        .date_var = date,
        .by       = "month", # Setup for monthly aggregation
        # Summarization
        value  = max(value)
    )
```

