---
title: "summarise-by-time"
author: "Matt Rosinski"
date: "2022-07-16"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summarise snow grouping by the start of each month
```{python}
import pandas as pd
url = 'https://bit.ly/snowfall-data'
    
alta_df = pd.read_csv(url)
    
dates = pd.to_datetime(alta_df.DATE)

snow = (alta_df
        .SNOW
        .rename(dates))

max_snow = (snow
 .resample('MS')
 .max())

mean_snow = (snow
 .resample('MS')
 .mean())
 
frame = {'max_snow': max_snow, 'mean_snow': mean_snow}
pd.DataFrame(frame)

```

```{python}
(snow
    .resample('MS')
    .mean())

```








```{r}
library(lubridate)
library(timetk)
library(tidyverse)
library(lubridate)
library(reticulate)

alta_df <- py$alta_df %>%
    select(DATE, SNOW) %>%
    mutate(DATE = ymd(DATE)) 

alta_df %>%
    summarise_by_time(.date_var = DATE,
                      .by = "month", .type = "floor",
                      max_snow = max(SNOW, na.rm = TRUE),
                      mean_snow = mean(SNOW, na.rm = TRUE)
                      )


```



```{r}






```

