---
title: "tidy data"
output: 
  html_document: 
    df_print: tibble
date: "2022-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# For other examples see:
# https://kwstat.github.io/untidydata2/articles/untidy-spreadsheet-example.html#raw-data

```

# Find the number one songs by week
```{r}

library(tidyverse)

data("billboard")

billboard <-  billboard %>% 
    mutate(across(contains("wk"), ~ as.numeric(.x)))

billboard_long <- billboard %>% 
    pivot_longer(cols = wk1:wk76, 
                 names_to = 'week',
                 values_to = 'rank', 
                 values_drop_na = TRUE) %>% 
    mutate(week = str_remove(week, "wk") %>% as.integer(),
           date = as.Date(date.entered) + 7 * (week - 1),
           date.entered = NULL) %>% 
    arrange(artist, track, week)

number_ones <- billboard_long %>% 
    filter(rank == 1) %>% 
    arrange(date)

number_ones %>% slice_head(n = 10)
```


```{r}
billboard %>% View()
```

```{r}
number_ones %>%  View()


```


```{python}

import pandas as pd

billboard = r.billboard

columns = billboard.columns[3:]

billboard_long = (billboard
    .melt(id_vars = ['artist', 'track', 'date.entered'], 
            value_vars = columns, 
            var_name = 'week',
            value_name ='rank')
    .dropna()
    .reset_index(drop = True)
    .assign(week = lambda x: x['week'].str.replace('wk', "").astype('int'))
    .assign(date = lambda x: pd.to_datetime(x['date.entered']) + \
            7*pd.to_timedelta((x['week'] - 1), unit='d'))
    .drop('date.entered', axis=1)
    .sort_values(['artist', 'track'])

)

number_ones = (billboard_long
    .query('rank == 1')
    .sort_values('date'))
    
number_ones.head(10)

```



```{python}
billboard
```




























